config-version: 2

name: 'google_ads_houseware'
version: '1.0.0'

profile: 'google_ads_houseware'

models:
  google_ads_houseware:
      +materialized: view

vars:
  # Optional configs to provide custom schemas
  google_ads_schema: TEST_GOOGLE_ADS
  google_ads_database: HOUSEWARE_HOUSEWARE

  google_ads_houseware:
    ad_stats: "{{ ref('stg_google_ads__ad_stats') }}"
    account_history: "{{ ref('stg_google_ads__account_history') }}"
    campaign_history: "{{ ref('stg_google_ads__campaign_history') }}"
    ad_group_history: "{{ ref('stg_google_ads__ad_group_history') }}"
    ad_history: "{{ ref('stg_google_ads__ad_history') }}"

    # Set boolean flag to read the latest info of Ads/Accounts/Campaigns/Ad Groups
    # from source tables. TRUE by default
    # see_most_recent_record:
