version: 2

sources:
  - name: google_ads
    schema: "{{ var('google_ads_schema', target.database) }}"
    database: "{{ var('google_ads_database', 'fivetran_google_ads') }}"

    tables:
      - name: AD_STATS
      - name: AD_HISTORY


models: []
