version: 2

sources:
  - name: google_ads
    schema: "{{ var('google_ads_schema', 'fivetran_google_ads') }}"
    database: "{{ var('google_ads_database', target.database) }}"

    tables:
      - name: ad_stats
      - name: ad_history


models: []
